id: 01a0f43e-d1f9-735e-b324-29948550f0f2
version: 1
name: New Mock
slug: new-mock-92d1f
enableSession: true
protocol: http
port: 4500
autoRestartOnChange: true
logging:
  level: verbose
  showBody: true
scenarios:
  - name: default
    path: ./default.js
    default: true
